/**
 * DiscussNet SSP — 全自治体の tenantId 取得ライブテスト
 *
 * 実際のサーバーに接続して tenant.js を取得し、tenantId が正しく解析できることを検証する。
 * ネットワークアクセスを伴うため、CI では実行しない。
 *
 *   bun run --cwd packages/scrapers vitest run schedule.live
 */
import { describe, expect, test } from "vitest";
import { fetchTenantId } from "./schedule";

// --- ssp.kaigiroku.net テナント ---

const SSP_TENANTS: Array<{ slug: string; expectedTenantId: number; name: string }> = [
  { slug: "hakodate", expectedTenantId: 537, name: "函館市" },
  { slug: "asahikawa", expectedTenantId: 529, name: "旭川市" },
  { slug: "muroran", expectedTenantId: 436, name: "室蘭市" },
  { slug: "kushiro", expectedTenantId: 532, name: "釧路市" },
  { slug: "obihiro", expectedTenantId: 535, name: "帯広市" },
  { slug: "kitami", expectedTenantId: 483, name: "北見市" },
  { slug: "tomakomai", expectedTenantId: 536, name: "苫小牧市" },
  { slug: "wakkanai", expectedTenantId: 70, name: "稚内市" },
  { slug: "ashibetsu", expectedTenantId: 530, name: "芦別市" },
  { slug: "nayoro", expectedTenantId: 614, name: "名寄市" },
  { slug: "nemuro", expectedTenantId: 533, name: "根室市" },
  { slug: "chitose", expectedTenantId: 452, name: "千歳市" },
  { slug: "noboribetsu", expectedTenantId: 538, name: "登別市" },
  { slug: "eniwa", expectedTenantId: 89, name: "恵庭市" },
  { slug: "date", expectedTenantId: 542, name: "伊達市" },
  { slug: "kitahiroshima", expectedTenantId: 72, name: "北広島市" },
  { slug: "ishikari", expectedTenantId: 93, name: "石狩市" },
  { slug: "hokuto", expectedTenantId: 309, name: "北斗市" },
  { slug: "kutchan", expectedTenantId: 453, name: "倶知安町" },
  { slug: "kita", expectedTenantId: 395, name: "猿払村" },
  { slug: "mizuho", expectedTenantId: 523, name: "美幌町" },
  { slug: "atsuma", expectedTenantId: 167, name: "厚真町" },
  { slug: "hidakahokkaido", expectedTenantId: 71, name: "日高町" },
  { slug: "memuro", expectedTenantId: 454, name: "芽室町" },
  { slug: "towada", expectedTenantId: 82, name: "十和田市" },
  { slug: "mutsu", expectedTenantId: 596, name: "むつ市" },
  { slug: "morioka", expectedTenantId: 559, name: "盛岡市" },
  { slug: "miyako", expectedTenantId: 373, name: "宮古市" },
  { slug: "ofunato", expectedTenantId: 30, name: "大船渡市" },
  { slug: "hanamaki", expectedTenantId: 374, name: "花巻市" },
  { slug: "kitakami", expectedTenantId: 457, name: "北上市" },
  { slug: "kuji", expectedTenantId: 121, name: "久慈市" },
  { slug: "rikuzentakata", expectedTenantId: 32, name: "陸前高田市" },
  { slug: "kamaishi", expectedTenantId: 458, name: "釜石市" },
  { slug: "ninohe", expectedTenantId: 81, name: "二戸市" },
  { slug: "oshu", expectedTenantId: 133, name: "奥州市" },
  { slug: "takizawa", expectedTenantId: 31, name: "滝沢市" },
  { slug: "shizukuishi", expectedTenantId: 80, name: "雫石町" },
  { slug: "shiwa", expectedTenantId: 375, name: "紫波町" },
  { slug: "kanegasaki", expectedTenantId: 88, name: "金ケ崎町" },
  { slug: "ichinohe", expectedTenantId: 620, name: "一戸町" },
  { slug: "prefmiyagi", expectedTenantId: 354, name: "宮城県" },
  { slug: "ishinomaki", expectedTenantId: 33, name: "石巻市" },
  { slug: "higashimatsushima", expectedTenantId: 187, name: "東松島市" },
  { slug: "oosaki", expectedTenantId: 376, name: "大崎市" },
  { slug: "prefakita", expectedTenantId: 408, name: "秋田県" },
  { slug: "noshiro", expectedTenantId: 214, name: "能代市" },
  { slug: "yokote", expectedTenantId: 615, name: "横手市" },
  { slug: "oga", expectedTenantId: 285, name: "男鹿市" },
  { slug: "yuzawa", expectedTenantId: 389, name: "湯沢市" },
  { slug: "yurihonjo", expectedTenantId: 227, name: "由利本荘市" },
  { slug: "kitaakita", expectedTenantId: 286, name: "北秋田市" },
  { slug: "semboku", expectedTenantId: 174, name: "仙北市" },
  { slug: "prefyamagata", expectedTenantId: 466, name: "山形県" },
  { slug: "tsuruoka", expectedTenantId: 552, name: "鶴岡市" },
  { slug: "sakata", expectedTenantId: 143, name: "酒田市" },
  { slug: "murayama", expectedTenantId: 377, name: "村山市" },
  { slug: "tendo", expectedTenantId: 467, name: "天童市" },
  { slug: "mamurogawa", expectedTenantId: 629, name: "真室川町" },
  { slug: "shounai", expectedTenantId: 135, name: "庄内町" },
  { slug: "fukushima", expectedTenantId: 69, name: "福島県" },
  { slug: "aizuwakamatsu", expectedTenantId: 68, name: "会津若松市" },
  { slug: "koriyama", expectedTenantId: 190, name: "郡山市" },
  { slug: "iwaki", expectedTenantId: 386, name: "いわき市" },
  { slug: "shirakawa", expectedTenantId: 155, name: "白河市" },
  { slug: "soma", expectedTenantId: 172, name: "相馬市" },
  { slug: "nihonmatsu", expectedTenantId: 171, name: "二本松市" },
  { slug: "tamura", expectedTenantId: 313, name: "田村市" },
  { slug: "minamisoma", expectedTenantId: 234, name: "南相馬市" },
  { slug: "datecity", expectedTenantId: 199, name: "伊達市" },
  { slug: "motomiya", expectedTenantId: 198, name: "本宮市" },
  { slug: "kunimi", expectedTenantId: 469, name: "国見町" },
  { slug: "saimisato", expectedTenantId: 46, name: "会津美里町" },
  { slug: "nishigo", expectedTenantId: 626, name: "西郷村" },
  { slug: "izumizaki", expectedTenantId: 154, name: "泉崎村" },
  { slug: "nakajima", expectedTenantId: 613, name: "中島村" },
  { slug: "yabuki", expectedTenantId: 349, name: "矢吹町" },
  { slug: "tanagura", expectedTenantId: 201, name: "棚倉町" },
  { slug: "yamatsuri", expectedTenantId: 128, name: "矢祭町" },
  { slug: "hirata", expectedTenantId: 127, name: "平田村" },
  { slug: "ino", expectedTenantId: 565, name: "小野町" },
  { slug: "kawauchi", expectedTenantId: 289, name: "川内村" },
  { slug: "mito", expectedTenantId: 215, name: "水戸市" },
  { slug: "tsuchiura", expectedTenantId: 578, name: "土浦市" },
  { slug: "koga", expectedTenantId: 76, name: "古河市" },
  { slug: "yuki", expectedTenantId: 582, name: "結城市" },
  { slug: "ryugasaki", expectedTenantId: 470, name: "龍ケ崎市" },
  { slug: "takahagi", expectedTenantId: 49, name: "高萩市" },
  { slug: "kitaibaraki", expectedTenantId: 587, name: "北茨城市" },
  { slug: "kashima", expectedTenantId: 28, name: "鹿嶋市" },
  { slug: "itako", expectedTenantId: 132, name: "潮来市" },
  { slug: "hitachiomiya", expectedTenantId: 157, name: "常陸大宮市" },
  { slug: "naka", expectedTenantId: 338, name: "那珂市" },
  { slug: "chikusei", expectedTenantId: 29, name: "筑西市" },
  { slug: "bando", expectedTenantId: 293, name: "坂東市" },
  { slug: "kasumigaura", expectedTenantId: 320, name: "かすみがうら市" },
  { slug: "kamisu", expectedTenantId: 292, name: "神栖市" },
  { slug: "namegata", expectedTenantId: 294, name: "行方市" },
  { slug: "hokota", expectedTenantId: 95, name: "鉾田市" },
  { slug: "omitama", expectedTenantId: 295, name: "小美玉市" },
  { slug: "ibaraki", expectedTenantId: 296, name: "茨城町" },
  { slug: "tokai", expectedTenantId: 297, name: "東海村" },
  { slug: "daigo", expectedTenantId: 298, name: "大子町" },
  { slug: "ashikaga", expectedTenantId: 409, name: "足利市" },
  { slug: "tochigi", expectedTenantId: 65, name: "栃木市" },
  { slug: "sano", expectedTenantId: 97, name: "佐野市" },
  { slug: "nikko", expectedTenantId: 67, name: "日光市" },
  { slug: "oyama", expectedTenantId: 64, name: "小山市" },
  { slug: "moka", expectedTenantId: 96, name: "真岡市" },
  { slug: "ohtawara", expectedTenantId: 496, name: "大田原市" },
  { slug: "yaita", expectedTenantId: 384, name: "矢板市" },
  { slug: "nasushiobara", expectedTenantId: 163, name: "那須塩原市" },
  { slug: "sakura", expectedTenantId: 152, name: "さくら市" },
  { slug: "shimotsuke", expectedTenantId: 299, name: "下野市" },
  { slug: "mashiko", expectedTenantId: 79, name: "益子町" },
  { slug: "ichikai", expectedTenantId: 170, name: "市貝町" },
  { slug: "haga", expectedTenantId: 383, name: "芳賀町" },
  { slug: "mibu", expectedTenantId: 301, name: "壬生町" },
  { slug: "nogi", expectedTenantId: 302, name: "野木町" },
  { slug: "shioya", expectedTenantId: 303, name: "塩谷町" },
  { slug: "takanezawa", expectedTenantId: 216, name: "高根沢町" },
  { slug: "nasu", expectedTenantId: 66, name: "那須町" },
  { slug: "kiryu", expectedTenantId: 74, name: "桐生市" },
  { slug: "tatebayashi", expectedTenantId: 35, name: "館林市" },
  { slug: "shibukawa", expectedTenantId: 36, name: "渋川市" },
  { slug: "tomioka", expectedTenantId: 37, name: "富岡市" },
  { slug: "annaka", expectedTenantId: 34, name: "安中市" },
  { slug: "midori", expectedTenantId: 603, name: "みどり市" },
  { slug: "oizumi", expectedTenantId: 126, name: "大泉町" },
  { slug: "prefsaitama", expectedTenantId: 350, name: "埼玉県" },
  { slug: "saitama", expectedTenantId: 134, name: "さいたま市" },
  { slug: "kumagaya", expectedTenantId: 94, name: "熊谷市" },
  { slug: "kawaguchi", expectedTenantId: 366, name: "川口市" },
  { slug: "gyoda", expectedTenantId: 351, name: "行田市" },
  { slug: "chichibu", expectedTenantId: 41, name: "秩父市" },
  { slug: "tokorozawa", expectedTenantId: 213, name: "所沢市" },
  { slug: "hanno", expectedTenantId: 601, name: "飯能市" },
  { slug: "kazo", expectedTenantId: 219, name: "加須市" },
  { slug: "honjo", expectedTenantId: 48, name: "本庄市" },
  { slug: "higashimatsuyama", expectedTenantId: 43, name: "東松山市" },
  { slug: "hanyu", expectedTenantId: 159, name: "羽生市" },
  { slug: "kounosu", expectedTenantId: 85, name: "鴻巣市" },
  { slug: "fukaya", expectedTenantId: 40, name: "深谷市" },
  { slug: "ageo", expectedTenantId: 39, name: "上尾市" },
  { slug: "koshigaya", expectedTenantId: 503, name: "越谷市" },
  { slug: "asaka", expectedTenantId: 217, name: "朝霞市" },
  { slug: "shiki", expectedTenantId: 381, name: "志木市" },
  { slug: "wako", expectedTenantId: 382, name: "和光市" },
  { slug: "okegawa", expectedTenantId: 184, name: "桶川市" },
  { slug: "kuki", expectedTenantId: 534, name: "久喜市" },
  { slug: "kitamoto", expectedTenantId: 300, name: "北本市" },
  { slug: "yashio", expectedTenantId: 233, name: "八潮市" },
  { slug: "fujimi", expectedTenantId: 47, name: "富士見市" },
  { slug: "hasuda", expectedTenantId: 51, name: "蓮田市" },
  { slug: "sakado", expectedTenantId: 348, name: "坂戸市" },
  { slug: "satte", expectedTenantId: 182, name: "幸手市" },
  { slug: "tsurugashima", expectedTenantId: 42, name: "鶴ヶ島市" },
  { slug: "saihidaka", expectedTenantId: 44, name: "日高市" },
  { slug: "yoshikawa", expectedTenantId: 230, name: "吉川市" },
  { slug: "fujimino", expectedTenantId: 24, name: "ふじみ野市" },
  { slug: "shiraoka", expectedTenantId: 45, name: "白岡市" },
  { slug: "inamachi", expectedTenantId: 218, name: "伊奈町" },
  { slug: "miyoshi", expectedTenantId: 38, name: "三芳町" },
  { slug: "moroyama", expectedTenantId: 50, name: "毛呂山町" },
  { slug: "ogose", expectedTenantId: 75, name: "越生町" },
  { slug: "ogawa", expectedTenantId: 87, name: "小川町" },
  { slug: "kawajima", expectedTenantId: 175, name: "川島町" },
  { slug: "yoshimi", expectedTenantId: 17, name: "吉見町" },
  { slug: "hatoyama", expectedTenantId: 471, name: "鳩山町" },
  { slug: "higashichichibu", expectedTenantId: 91, name: "東秩父村" },
  { slug: "kamikawa", expectedTenantId: 73, name: "神川町" },
  { slug: "yorii", expectedTenantId: 232, name: "寄居町" },
  { slug: "miyashiro", expectedTenantId: 224, name: "宮代町" },
  { slug: "sugito", expectedTenantId: 78, name: "杉戸町" },
  { slug: "choshi", expectedTenantId: 549, name: "銚子市" },
  { slug: "ichikawa", expectedTenantId: 633, name: "市川市" },
  { slug: "tateyama", expectedTenantId: 548, name: "館山市" },
  { slug: "matsudo", expectedTenantId: 392, name: "松戸市" },
  { slug: "noda", expectedTenantId: 62, name: "野田市" },
  { slug: "narita", expectedTenantId: 183, name: "成田市" },
  { slug: "togane", expectedTenantId: 145, name: "東金市" },
  { slug: "narashino", expectedTenantId: 161, name: "習志野市" },
  { slug: "kashiwa", expectedTenantId: 61, name: "柏市" },
  { slug: "ichihara", expectedTenantId: 195, name: "市原市" },
  { slug: "nagareyama", expectedTenantId: 63, name: "流山市" },
  { slug: "yachiyo", expectedTenantId: 229, name: "八千代市" },
  { slug: "abiko", expectedTenantId: 391, name: "我孫子市" },
  { slug: "kamagaya", expectedTenantId: 98, name: "鎌ケ谷市" },
  { slug: "kimitsu", expectedTenantId: 142, name: "君津市" },
  { slug: "urayasu", expectedTenantId: 141, name: "浦安市" },
  { slug: "yotsukaido", expectedTenantId: 461, name: "四街道市" },
  { slug: "sodegaura", expectedTenantId: 60, name: "袖ケ浦市" },
  { slug: "inzai", expectedTenantId: 59, name: "印西市" },
  { slug: "tomisato", expectedTenantId: 304, name: "富里市" },
  { slug: "sosa", expectedTenantId: 212, name: "匝瑳市" },
  { slug: "katori", expectedTenantId: 144, name: "香取市" },
  { slug: "isumi", expectedTenantId: 192, name: "いすみ市" },
  { slug: "oamishirasato", expectedTenantId: 225, name: "大網白里市" },
  { slug: "shisui", expectedTenantId: 482, name: "酒々井町" },
  { slug: "kujukuri", expectedTenantId: 604, name: "九十九里町" },
  { slug: "shibayama", expectedTenantId: 346, name: "芝山町" },
  { slug: "shinjuku", expectedTenantId: 211, name: "新宿区" },
  { slug: "sumida", expectedTenantId: 396, name: "墨田区" },
  { slug: "shibuya", expectedTenantId: 394, name: "渋谷区" },
  { slug: "arakawa", expectedTenantId: 577, name: "荒川区" },
  { slug: "nerima", expectedTenantId: 367, name: "練馬区" },
  { slug: "tachikawa", expectedTenantId: 368, name: "立川市" },
  { slug: "ome", expectedTenantId: 580, name: "青梅市" },
  { slug: "akishima", expectedTenantId: 21, name: "昭島市" },
  { slug: "kodaira", expectedTenantId: 165, name: "小平市" },
  { slug: "higashiyamato", expectedTenantId: 624, name: "東大和市" },
  { slug: "kiyose", expectedTenantId: 197, name: "清瀬市" },
  { slug: "musashimurayama", expectedTenantId: 220, name: "武蔵村山市" },
  { slug: "ogasawara", expectedTenantId: 600, name: "小笠原村" },
  { slug: "prefkanagawa", expectedTenantId: 369, name: "神奈川県" },
  { slug: "sagamihara", expectedTenantId: 400, name: "相模原市" },
  { slug: "yokosuka", expectedTenantId: 231, name: "横須賀市" },
  { slug: "odawara", expectedTenantId: 402, name: "小田原市" },
  { slug: "zushi", expectedTenantId: 221, name: "逗子市" },
  { slug: "ayase", expectedTenantId: 576, name: "綾瀬市" },
  { slug: "aikawa", expectedTenantId: 139, name: "愛川町" },
  { slug: "prefniigata", expectedTenantId: 333, name: "新潟県" },
  { slug: "ojiya", expectedTenantId: 318, name: "小千谷市" },
  { slug: "tokamachi", expectedTenantId: 54, name: "十日町市" },
  { slug: "tsubame", expectedTenantId: 83, name: "燕市" },
  { slug: "myoko", expectedTenantId: 77, name: "妙高市" },
  { slug: "gosen", expectedTenantId: 86, name: "五泉市" },
  { slug: "joetsu", expectedTenantId: 55, name: "上越市" },
  { slug: "tainai", expectedTenantId: 84, name: "胎内市" },
  { slug: "aga", expectedTenantId: 169, name: "阿賀町" },
  { slug: "oyabe", expectedTenantId: 153, name: "小矢部市" },
  { slug: "nanto", expectedTenantId: 472, name: "南砺市" },
  { slug: "imizu", expectedTenantId: 308, name: "射水市" },
  { slug: "kanazawa", expectedTenantId: 399, name: "金沢市" },
  { slug: "nanao", expectedTenantId: 307, name: "七尾市" },
  { slug: "wajima", expectedTenantId: 228, name: "輪島市" },
  { slug: "kaga", expectedTenantId: 173, name: "加賀市" },
  { slug: "hakusan", expectedTenantId: 202, name: "白山市" },
  { slug: "nonoichi", expectedTenantId: 306, name: "野々市市" },
  { slug: "fukui", expectedTenantId: 493, name: "福井市" },
  { slug: "obama", expectedTenantId: 473, name: "小浜市" },
  { slug: "ono", expectedTenantId: 555, name: "大野市" },
  { slug: "ohi", expectedTenantId: 522, name: "おおい町" },
  { slug: "fujiyoshida", expectedTenantId: 312, name: "富士吉田市" },
  { slug: "tsuru", expectedTenantId: 138, name: "都留市" },
  { slug: "yamanashi", expectedTenantId: 226, name: "山梨市" },
  { slug: "otsuki", expectedTenantId: 52, name: "大月市" },
  { slug: "nirasaki", expectedTenantId: 160, name: "韮崎市" },
  { slug: "cityhokuto", expectedTenantId: 598, name: "北杜市" },
  { slug: "kai", expectedTenantId: 200, name: "甲斐市" },
  { slug: "uenohara", expectedTenantId: 205, name: "上野原市" },
  { slug: "koshu", expectedTenantId: 180, name: "甲州市" },
  { slug: "chuo", expectedTenantId: 137, name: "中央市" },
  { slug: "ichikawamisato", expectedTenantId: 136, name: "市川三郷町" },
  { slug: "showa", expectedTenantId: 290, name: "昭和町" },
  { slug: "fujikawaguchiko", expectedTenantId: 222, name: "富士河口湖町" },
  { slug: "nagano", expectedTenantId: 189, name: "長野市" },
  { slug: "matsumoto", expectedTenantId: 162, name: "松本市" },
  { slug: "ueda", expectedTenantId: 90, name: "上田市" },
  { slug: "okaya", expectedTenantId: 148, name: "岡谷市" },
  { slug: "iida", expectedTenantId: 151, name: "飯田市" },
  { slug: "suzaka", expectedTenantId: 186, name: "須坂市" },
  { slug: "komoro", expectedTenantId: 164, name: "小諸市" },
  { slug: "ina", expectedTenantId: 147, name: "伊那市" },
  { slug: "komagane", expectedTenantId: 521, name: "駒ヶ根市" },
  { slug: "nakano", expectedTenantId: 208, name: "中野市" },
  { slug: "omachi", expectedTenantId: 150, name: "大町市" },
  { slug: "iiyama", expectedTenantId: 156, name: "飯山市" },
  { slug: "chino", expectedTenantId: 149, name: "茅野市" },
  { slug: "shiojiri", expectedTenantId: 191, name: "塩尻市" },
  { slug: "saku", expectedTenantId: 177, name: "佐久市" },
  { slug: "chikuma", expectedTenantId: 166, name: "千曲市" },
  { slug: "tomi", expectedTenantId: 419, name: "東御市" },
  { slug: "azumino", expectedTenantId: 146, name: "安曇野市" },
  { slug: "sakuho", expectedTenantId: 310, name: "佐久穂町" },
  { slug: "karuizawa", expectedTenantId: 185, name: "軽井沢町" },
  { slug: "minowa", expectedTenantId: 550, name: "箕輪町" },
  { slug: "prefgifu", expectedTenantId: 352, name: "岐阜県" },
  { slug: "takayama", expectedTenantId: 591, name: "高山市" },
  { slug: "tajimi", expectedTenantId: 404, name: "多治見市" },
  { slug: "seki", expectedTenantId: 474, name: "関市" },
  { slug: "nakatsugawa", expectedTenantId: 575, name: "中津川市" },
  { slug: "hashima", expectedTenantId: 158, name: "羽島市" },
  { slug: "minokamo", expectedTenantId: 475, name: "美濃加茂市" },
  { slug: "toki", expectedTenantId: 583, name: "土岐市" },
  { slug: "hamamatsu", expectedTenantId: 405, name: "浜松市" },
  { slug: "atami", expectedTenantId: 378, name: "熱海市" },
  { slug: "mishima", expectedTenantId: 406, name: "三島市" },
  { slug: "fujinomiya", expectedTenantId: 58, name: "富士宮市" },
  { slug: "iwata", expectedTenantId: 140, name: "磐田市" },
  { slug: "susono", expectedTenantId: 57, name: "裾野市" },
  { slug: "izu", expectedTenantId: 630, name: "伊豆市" },
  { slug: "omaezaki", expectedTenantId: 56, name: "御前崎市" },
  { slug: "kikugawa", expectedTenantId: 248, name: "菊川市" },
  { slug: "izunokuni", expectedTenantId: 223, name: "伊豆の国市" },
  { slug: "kannami", expectedTenantId: 168, name: "函南町" },
  { slug: "nagoya", expectedTenantId: 207, name: "名古屋市" },
  { slug: "toyohashi", expectedTenantId: 410, name: "豊橋市" },
  { slug: "okazaki", expectedTenantId: 194, name: "岡崎市" },
  { slug: "ichinomiya", expectedTenantId: 411, name: "一宮市" },
  { slug: "seto", expectedTenantId: 420, name: "瀬戸市" },
  { slug: "handa", expectedTenantId: 176, name: "半田市" },
  { slug: "kasugai", expectedTenantId: 476, name: "春日井市" },
  { slug: "toyokawa", expectedTenantId: 412, name: "豊川市" },
  { slug: "kariya", expectedTenantId: 181, name: "刈谷市" },
  { slug: "anjo", expectedTenantId: 413, name: "安城市" },
  { slug: "gamagori", expectedTenantId: 414, name: "蒲郡市" },
  { slug: "tokoname", expectedTenantId: 131, name: "常滑市" },
  { slug: "kounan", expectedTenantId: 130, name: "江南市" },
  { slug: "chita", expectedTenantId: 206, name: "知多市" },
  { slug: "owariasahi", expectedTenantId: 415, name: "尾張旭市" },
  { slug: "nisshin", expectedTenantId: 477, name: "日進市" },
  { slug: "tahara", expectedTenantId: 416, name: "田原市" },
  { slug: "kitanagoya", expectedTenantId: 574, name: "北名古屋市" },
  { slug: "toyoyama", expectedTenantId: 478, name: "豊山町" },
  { slug: "oguchi", expectedTenantId: 319, name: "大口町" },
  { slug: "tobishima2", expectedTenantId: 480, name: "飛島村" },
  { slug: "agui", expectedTenantId: 481, name: "阿久比町" },
  { slug: "higashiura", expectedTenantId: 331, name: "東浦町" },
  { slug: "taketoyo", expectedTenantId: 485, name: "武豊町" },
  { slug: "tsu", expectedTenantId: 418, name: "津市" },
  { slug: "ise", expectedTenantId: 330, name: "伊勢市" },
  { slug: "matsusaka", expectedTenantId: 178, name: "松阪市" },
  { slug: "nabari", expectedTenantId: 278, name: "名張市" },
  { slug: "toba", expectedTenantId: 287, name: "鳥羽市" },
  { slug: "odai", expectedTenantId: 422, name: "大台町" },
  { slug: "nagahama", expectedTenantId: 277, name: "長浜市" },
  { slug: "omihachiman", expectedTenantId: 276, name: "近江八幡市" },
  { slug: "koka", expectedTenantId: 486, name: "甲賀市" },
  { slug: "konan", expectedTenantId: 556, name: "湖南市" },
  { slug: "takashima", expectedTenantId: 390, name: "高島市" },
  { slug: "kyoto", expectedTenantId: 355, name: "京都市" },
  { slug: "maizuru", expectedTenantId: 423, name: "舞鶴市" },
  { slug: "uji", expectedTenantId: 484, name: "宇治市" },
  { slug: "kameoka", expectedTenantId: 288, name: "亀岡市" },
  { slug: "kyotanabe", expectedTenantId: 425, name: "京田辺市" },
  { slug: "ujitawara", expectedTenantId: 612, name: "宇治田原町" },
  { slug: "yosano", expectedTenantId: 487, name: "与謝野町" },
  { slug: "prefosaka", expectedTenantId: 315, name: "大阪府" },
  { slug: "cityosaka", expectedTenantId: 357, name: "大阪市" },
  { slug: "ikeda", expectedTenantId: 353, name: "池田市" },
  { slug: "suita", expectedTenantId: 427, name: "吹田市" },
  { slug: "izumiotsu", expectedTenantId: 428, name: "泉大津市" },
  { slug: "kaizuka", expectedTenantId: 429, name: "貝塚市" },
  { slug: "izumisano", expectedTenantId: 488, name: "泉佐野市" },
  { slug: "tondabayashi", expectedTenantId: 431, name: "富田林市" },
  { slug: "kawachinagano", expectedTenantId: 433, name: "河内長野市" },
  { slug: "matsubara", expectedTenantId: 438, name: "松原市" },
  { slug: "izumi", expectedTenantId: 316, name: "和泉市" },
  { slug: "minoh", expectedTenantId: 356, name: "箕面市" },
  { slug: "kashiwara", expectedTenantId: 440, name: "柏原市" },
  { slug: "settsu", expectedTenantId: 489, name: "摂津市" },
  { slug: "takaishi", expectedTenantId: 417, name: "高石市" },
  { slug: "fujiidera", expectedTenantId: 441, name: "藤井寺市" },
  { slug: "shijonawate", expectedTenantId: 442, name: "四條畷市" },
  { slug: "katano", expectedTenantId: 443, name: "交野市" },
  { slug: "osakasayama", expectedTenantId: 444, name: "大阪狭山市" },
  { slug: "hannan", expectedTenantId: 445, name: "阪南市" },
  { slug: "amagasaki", expectedTenantId: 421, name: "尼崎市" },
  { slug: "ashiya", expectedTenantId: 204, name: "芦屋市" },
  { slug: "miki", expectedTenantId: 272, name: "三木市" },
  { slug: "kawanishi", expectedTenantId: 305, name: "川西市" },
  { slug: "sanda", expectedTenantId: 362, name: "三田市" },
  { slug: "kasai", expectedTenantId: 449, name: "加西市" },
  { slug: "kato", expectedTenantId: 361, name: "加東市" },
  { slug: "taka", expectedTenantId: 249, name: "多可町" },
  { slug: "prefnara", expectedTenantId: 332, name: "奈良県" },
  { slug: "narashi", expectedTenantId: 358, name: "奈良市" },
  { slug: "yamatokoriyama", expectedTenantId: 490, name: "大和郡山市" },
  { slug: "tenri", expectedTenantId: 203, name: "天理市" },
  { slug: "gojo", expectedTenantId: 347, name: "五條市" },
  { slug: "gose", expectedTenantId: 328, name: "御所市" },
  { slug: "kashiba", expectedTenantId: 514, name: "香芝市" },
  { slug: "tawaramoto", expectedTenantId: 609, name: "田原本町" },
  { slug: "oji", expectedTenantId: 459, name: "王寺町" },
  { slug: "wakayama", expectedTenantId: 398, name: "和歌山市" },
  { slug: "kainan", expectedTenantId: 336, name: "海南市" },
  { slug: "gobo", expectedTenantId: 335, name: "御坊市" },
  { slug: "shingu", expectedTenantId: 334, name: "新宮市" },
  { slug: "inami", expectedTenantId: 337, name: "印南町" },
  { slug: "iwami", expectedTenantId: 273, name: "岩美町" },
  { slug: "matsue", expectedTenantId: 439, name: "松江市" },
  { slug: "hamada", expectedTenantId: 262, name: "浜田市" },
  { slug: "masuda", expectedTenantId: 263, name: "益田市" },
  { slug: "yasugi", expectedTenantId: 260, name: "安来市" },
  { slug: "gotsu", expectedTenantId: 261, name: "江津市" },
  { slug: "prefokayama", expectedTenantId: 455, name: "岡山県" },
  { slug: "okayama", expectedTenantId: 359, name: "岡山市" },
  { slug: "kurashiki", expectedTenantId: 456, name: "倉敷市" },
  { slug: "tsuyama", expectedTenantId: 271, name: "津山市" },
  { slug: "tamano", expectedTenantId: 268, name: "玉野市" },
  { slug: "kasaoka", expectedTenantId: 257, name: "笠岡市" },
  { slug: "ibara", expectedTenantId: 258, name: "井原市" },
  { slug: "soja", expectedTenantId: 252, name: "総社市" },
  { slug: "takahashi", expectedTenantId: 254, name: "高梁市" },
  { slug: "bizen", expectedTenantId: 592, name: "備前市" },
  { slug: "setouchi", expectedTenantId: 513, name: "瀬戸内市" },
  { slug: "akaiwa", expectedTenantId: 509, name: "赤磐市" },
  { slug: "maniwa", expectedTenantId: 253, name: "真庭市" },
  { slug: "mimasaka", expectedTenantId: 617, name: "美作市" },
  { slug: "asakuchi", expectedTenantId: 256, name: "浅口市" },
  { slug: "hayashima", expectedTenantId: 255, name: "早島町" },
  { slug: "satosho", expectedTenantId: 259, name: "里庄町" },
  { slug: "kagamino", expectedTenantId: 363, name: "鏡野町" },
  { slug: "misaki", expectedTenantId: 450, name: "美咲町" },
  { slug: "kure", expectedTenantId: 491, name: "呉市" },
  { slug: "mihara", expectedTenantId: 506, name: "三原市" },
  { slug: "onomichi", expectedTenantId: 274, name: "尾道市" },
  { slug: "fukuyama", expectedTenantId: 505, name: "福山市" },
  { slug: "shobara", expectedTenantId: 339, name: "庄原市" },
  { slug: "higashihiroshima", expectedTenantId: 564, name: "東広島市" },
  { slug: "jinsekikougen", expectedTenantId: 403, name: "神石高原町" },
  { slug: "prefyamaguchi", expectedTenantId: 599, name: "山口県" },
  { slug: "shimonoseki", expectedTenantId: 124, name: "下関市" },
  { slug: "ube", expectedTenantId: 117, name: "宇部市" },
  { slug: "hagi", expectedTenantId: 595, name: "萩市" },
  { slug: "hofu", expectedTenantId: 120, name: "防府市" },
  { slug: "kudamatsu", expectedTenantId: 116, name: "下松市" },
  { slug: "iwakuni", expectedTenantId: 101, name: "岩国市" },
  { slug: "nagato", expectedTenantId: 104, name: "長門市" },
  { slug: "yanai", expectedTenantId: 105, name: "柳井市" },
  { slug: "shunan", expectedTenantId: 103, name: "周南市" },
  { slug: "sanyoonoda", expectedTenantId: 102, name: "山陽小野田市" },
  { slug: "tokushimapref", expectedTenantId: 266, name: "徳島県" },
  { slug: "naruto", expectedTenantId: 265, name: "鳴門市" },
  { slug: "anan", expectedTenantId: 264, name: "阿南市" },
  { slug: "tmiyoshi", expectedTenantId: 280, name: "三好市" },
  { slug: "ishii", expectedTenantId: 267, name: "石井町" },
  { slug: "takamatsu", expectedTenantId: 561, name: "高松市" },
  { slug: "marugame", expectedTenantId: 515, name: "丸亀市" },
  { slug: "sakaide", expectedTenantId: 593, name: "坂出市" },
  { slug: "zentsuji", expectedTenantId: 594, name: "善通寺市" },
  { slug: "kanonji", expectedTenantId: 508, name: "観音寺市" },
  { slug: "matsuyama", expectedTenantId: 279, name: "松山市" },
  { slug: "uwajima", expectedTenantId: 340, name: "宇和島市" },
  { slug: "saijo", expectedTenantId: 507, name: "西条市" },
  { slug: "iyo", expectedTenantId: 269, name: "伊予市" },
  { slug: "shikokuchuo", expectedTenantId: 270, name: "四国中央市" },
  { slug: "toon", expectedTenantId: 129, name: "東温市" },
  { slug: "prefkochi", expectedTenantId: 494, name: "高知県" },
  { slug: "kochi", expectedTenantId: 566, name: "高知市" },
  { slug: "tosa", expectedTenantId: 553, name: "土佐市" },
  { slug: "shimanto", expectedTenantId: 531, name: "四万十市" },
  { slug: "jodo", expectedTenantId: 502, name: "仁淀川町" },
  { slug: "kitakyushu", expectedTenantId: 528, name: "北九州市" },
  { slug: "omuta", expectedTenantId: 324, name: "大牟田市" },
  { slug: "chikugo", expectedTenantId: 558, name: "筑後市" },
  { slug: "yukuhashi", expectedTenantId: 568, name: "行橋市" },
  { slug: "nakagawa", expectedTenantId: 527, name: "中間市" },
  { slug: "fukutsu", expectedTenantId: 560, name: "福津市" },
  { slug: "shime", expectedTenantId: 524, name: "志免町" },
  { slug: "okagaki", expectedTenantId: 122, name: "岡垣町" },
  { slug: "kanda", expectedTenantId: 123, name: "苅田町" },
  { slug: "miyakomachi", expectedTenantId: 118, name: "みやこ町" },
  { slug: "karatsu", expectedTenantId: 519, name: "唐津市" },
  { slug: "tosu", expectedTenantId: 545, name: "鳥栖市" },
  { slug: "taku", expectedTenantId: 518, name: "多久市" },
  { slug: "imari", expectedTenantId: 544, name: "伊万里市" },
  { slug: "genkai", expectedTenantId: 619, name: "玄海町" },
  { slug: "prefnagasaki", expectedTenantId: 460, name: "長崎県" },
  { slug: "sasebo", expectedTenantId: 462, name: "佐世保市" },
  { slug: "omura", expectedTenantId: 495, name: "大村市" },
  { slug: "hirado", expectedTenantId: 540, name: "平戸市" },
  { slug: "tsushima", expectedTenantId: 112, name: "対馬市" },
  { slug: "goto", expectedTenantId: 327, name: "五島市" },
  { slug: "saikai", expectedTenantId: 326, name: "西海市" },
  { slug: "unzen", expectedTenantId: 111, name: "雲仙市" },
  { slug: "minamishimabara", expectedTenantId: 325, name: "南島原市" },
  { slug: "prefkumamoto", expectedTenantId: 516, name: "熊本県" },
  { slug: "uto", expectedTenantId: 497, name: "宇土市" },
  { slug: "uki", expectedTenantId: 512, name: "宇城市" },
  { slug: "amakusa", expectedTenantId: 498, name: "天草市" },
  { slug: "prefoita", expectedTenantId: 499, name: "大分県" },
  { slug: "nakatsu", expectedTenantId: 109, name: "中津市" },
  { slug: "hita", expectedTenantId: 110, name: "日田市" },
  { slug: "usuki", expectedTenantId: 344, name: "臼杵市" },
  { slug: "taketa", expectedTenantId: 342, name: "竹田市" },
  { slug: "bungotakada", expectedTenantId: 602, name: "豊後高田市" },
  { slug: "kitsuki", expectedTenantId: 107, name: "杵築市" },
  { slug: "bungoohno", expectedTenantId: 345, name: "豊後大野市" },
  { slug: "kunisaki", expectedTenantId: 108, name: "国東市" },
  { slug: "kokonoe", expectedTenantId: 557, name: "九重町" },
  { slug: "miyazakipref", expectedTenantId: 251, name: "宮崎県" },
  { slug: "kobayashi", expectedTenantId: 193, name: "小林市" },
  { slug: "hyuga", expectedTenantId: 179, name: "日向市" },
  { slug: "saito", expectedTenantId: 343, name: "西都市" },
  { slug: "aya", expectedTenantId: 100, name: "綾町" },
  { slug: "shintomi", expectedTenantId: 114, name: "新富町" },
  { slug: "kadogawa", expectedTenantId: 115, name: "門川町" },
  { slug: "kagoshima", expectedTenantId: 539, name: "鹿児島市" },
  { slug: "kanoya", expectedTenantId: 250, name: "鹿屋市" },
  { slug: "satsumasendai", expectedTenantId: 501, name: "薩摩川内市" },
  { slug: "soo", expectedTenantId: 314, name: "曽於市" },
  { slug: "minamikyushu", expectedTenantId: 106, name: "南九州市" },
  { slug: "aira", expectedTenantId: 125, name: "姶良市" },
  { slug: "kimotsuki", expectedTenantId: 341, name: "肝付町" },
  { slug: "ginowan", expectedTenantId: 322, name: "宜野湾市" },
  { slug: "ishigaki", expectedTenantId: 541, name: "石垣市" },
  { slug: "urasoe", expectedTenantId: 504, name: "浦添市" },
  { slug: "nago", expectedTenantId: 511, name: "名護市" },
  { slug: "itoman", expectedTenantId: 567, name: "糸満市" },
  { slug: "okinawa", expectedTenantId: 563, name: "沖縄市" },
  { slug: "tomigusuku", expectedTenantId: 554, name: "豊見城市" },
  { slug: "uruma", expectedTenantId: 562, name: "うるま市" },
  { slug: "miyakojima", expectedTenantId: 546, name: "宮古島市" },
  { slug: "nanjo", expectedTenantId: 463, name: "南城市" },
  { slug: "higashi", expectedTenantId: 99, name: "東村" },
  { slug: "onna", expectedTenantId: 329, name: "恩納村" },
  { slug: "ginoza", expectedTenantId: 569, name: "宜野座村" },
  { slug: "yomitan", expectedTenantId: 510, name: "読谷村" },
  { slug: "kadena", expectedTenantId: 323, name: "嘉手納町" },
  { slug: "chatan", expectedTenantId: 321, name: "北谷町" },
  { slug: "kitanakagusuku", expectedTenantId: 627, name: "北中城村" },
  { slug: "nishihara", expectedTenantId: 464, name: "西原町" },
  { slug: "yonabaru", expectedTenantId: 547, name: "与那原町" },
  { slug: "kumejima", expectedTenantId: 611, name: "久米島町" },
  { slug: "yaese", expectedTenantId: 465, name: "八重瀬町" },
  { slug: "taketomi", expectedTenantId: 571, name: "竹富町" },
];

// --- smart.discussvision.net テナント ---

const SMART_TENANTS: Array<{ slug: string; expectedTenantId: number; name: string }> = [
  { slug: "kahoku", expectedTenantId: 396, name: "河北町" },
  { slug: "mogami", expectedTenantId: 87, name: "最上町" },
  { slug: "tozawa", expectedTenantId: 486, name: "戸沢村" },
  { slug: "kagamiishi", expectedTenantId: 685, name: "鏡石町" },
  { slug: "hanawa", expectedTenantId: 25, name: "塙町" },
  { slug: "namegawa", expectedTenantId: 570, name: "滑川町" },
  { slug: "mutsuzawa", expectedTenantId: 590, name: "睦沢町" },
  { slug: "niijima", expectedTenantId: 188, name: "新島村" },
  { slug: "chikusei", expectedTenantId: 516, name: "筑北村" },
  { slug: "nozawaonsen", expectedTenantId: 602, name: "野沢温泉村" },
  { slug: "tomika", expectedTenantId: 93, name: "富加町" },
  { slug: "nara", expectedTenantId: 258, name: "天川村" },
  { slug: "kami", expectedTenantId: 242, name: "香美市" },
  { slug: "nakatosa", expectedTenantId: 182, name: "中土佐町" },
  { slug: "ooki", expectedTenantId: 681, name: "大木町" },
  { slug: "miyazaki", expectedTenantId: 342, name: "美郷町" },
  { slug: "minamisatsuma", expectedTenantId: 320, name: "南さつま市" },
];

// --- self-hosted テナント ---

const SELF_HOSTED_TENANTS: Array<{
  slug: string;
  expectedTenantId: number;
  name: string;
  host: string;
}> = [
  {
    slug: "yokohama",
    expectedTenantId: 20,
    name: "横浜市",
    host: "http://giji.city.yokohama.lg.jp",
  },
];

describe("fetchTenantId — ssp.kaigiroku.net 全テナント", () => {
  test.each(SSP_TENANTS)(
    "$name ($slug) → tenantId=$expectedTenantId",
    async ({ slug, expectedTenantId }) => {
      const tenantId = await fetchTenantId(slug);
      expect(tenantId).toBe(expectedTenantId);
    },
    15_000,
  );
});

describe("fetchTenantId — smart.discussvision.net 全テナント", () => {
  test.each(SMART_TENANTS)(
    "$name ($slug) → tenantId=$expectedTenantId",
    async ({ slug, expectedTenantId }) => {
      const tenantJsUrl = `https://smart.discussvision.net/smart/tenant/${slug}/WebView/js/tenant.js`;
      const tenantId = await fetchTenantId(slug, undefined, tenantJsUrl);
      expect(tenantId).toBe(expectedTenantId);
    },
    15_000,
  );
});

describe("fetchTenantId — self-hosted 全テナント", () => {
  test.each(SELF_HOSTED_TENANTS)(
    "$name ($slug@$host) → tenantId=$expectedTenantId",
    async ({ slug, expectedTenantId, host }) => {
      const tenantId = await fetchTenantId(slug, host);
      expect(tenantId).toBe(expectedTenantId);
    },
    15_000,
  );
});
