name = "open-gikai-web"
main = "@tanstack/react-start/server-entry"
compatibility_date = "2026-03-05"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[vars]
BETTER_AUTH_URL = "https://opengikai.com"
CORS_ORIGIN = "https://opengikai.com"

[[hyperdrive]]
binding = "HYPERDRIVE"
# https://dash.cloudflare.com/7fb5eb6c9cdafa1bcf6d980c82ef81c8/workers/hyperdrive/f90a4be2e2fd41ae82fd55127b10e8ad
id = "f90a4be2e2fd41ae82fd55127b10e8ad"
# ローカル開発時だけ、DATABASE_URLに直接つなぐ
localConnectionString = "postgresql://postgres:postgres@127.0.0.1:54322/postgres"

[observability]
enabled = true