project_id = "open-gikai"

[api]
enabled = true
# Port to use for the API URL.
port = 54321
# APIからアクセスできるDBスキーマ
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
# APIが返す最大行数
max_rows = 1000

[api.tls]
# ローカルAPIをHTTPSにするか？
enabled = false

[db]
port = 54322
# migration diff用のシャドウポート
shadow_port = 54320
# postgresのバージョン
major_version = 17

[db.pooler]
# DBコネクションプーラー = Postgres接続を再利用して高速化する仕組み
# これを使わない場合、リクエストごとにDB接続を新規作成することになる
enabled = false
# プール接続用のポート
port = 54329
# 接続を再利用するタイミング
# transaction: トランザクション終了ごとに接続を返却する
# session: セッション終了まで接続を保持する
pool_mode = "transaction"
# DBへの最大同時接続数
default_pool_size = 20
# クライアント接続の最大数。
max_client_conn = 100

# [db.vault]
# secret_key = "env(SECRET_VALUE)"

[db.migrations]
enabled = false

[db.seed]
enabled = false

[realtime]
enabled = false

[studio]
enabled = false

[inbucket]
enabled = false

[storage]
enabled = false

[auth]
enabled = false

[edge_runtime]
enabled = false

[analytics]
enabled = false

# Experimental features may be deprecated any time
[experimental]
# Configures Postgres storage engine to use OrioleDB (S3)
orioledb_version = ""
# Configures S3 bucket URL, eg. <bucket_name>.s3-<region>.amazonaws.com
s3_host = "env(S3_HOST)"
# Configures S3 bucket region, eg. us-east-1
s3_region = "env(S3_REGION)"
# Configures AWS_ACCESS_KEY_ID for S3 bucket
s3_access_key = "env(S3_ACCESS_KEY)"
# Configures AWS_SECRET_ACCESS_KEY for S3 bucket
s3_secret_key = "env(S3_SECRET_KEY)"
