/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as MunicipalitiesIndexRouteImport } from './routes/municipalities/index'
import { Route as MeetingsIndexRouteImport } from './routes/meetings/index'
import { Route as MeetingsMeetingIdRouteImport } from './routes/meetings/$meetingId'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout/index'
import { Route as authSignUpIndexRouteImport } from './routes/(auth)/sign-up/index'
import { Route as authSignInIndexRouteImport } from './routes/(auth)/sign-in/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminLayoutScrapersIndexRouteImport } from './routes/admin/_layout/scrapers/index'
import { Route as AdminLayoutProgressIndexRouteImport } from './routes/admin/_layout/progress/index'
import { Route as AdminLayoutScrapersJobIdRouteImport } from './routes/admin/_layout/scrapers/$jobId'
import { Route as AdminLayoutProgressYearsRouteImport } from './routes/admin/_layout/progress/years'
import { Route as AdminLayoutProgressPrefecturesRouteImport } from './routes/admin/_layout/progress/prefectures'
import { Route as AdminLayoutProgressMunicipalitiesRouteImport } from './routes/admin/_layout/progress/municipalities'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const MunicipalitiesIndexRoute = MunicipalitiesIndexRouteImport.update({
  id: '/municipalities/',
  path: '/municipalities/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsIndexRoute = MeetingsIndexRouteImport.update({
  id: '/meetings/',
  path: '/meetings/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsMeetingIdRoute = MeetingsMeetingIdRouteImport.update({
  id: '/meetings/$meetingId',
  path: '/meetings/$meetingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const authSignUpIndexRoute = authSignUpIndexRouteImport.update({
  id: '/(auth)/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInIndexRoute = authSignInIndexRouteImport.update({
  id: '/(auth)/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutScrapersIndexRoute =
  AdminLayoutScrapersIndexRouteImport.update({
    id: '/scrapers/',
    path: '/scrapers/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutProgressIndexRoute =
  AdminLayoutProgressIndexRouteImport.update({
    id: '/progress/',
    path: '/progress/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutScrapersJobIdRoute =
  AdminLayoutScrapersJobIdRouteImport.update({
    id: '/scrapers/$jobId',
    path: '/scrapers/$jobId',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutProgressYearsRoute =
  AdminLayoutProgressYearsRouteImport.update({
    id: '/progress/years',
    path: '/progress/years',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutProgressPrefecturesRoute =
  AdminLayoutProgressPrefecturesRouteImport.update({
    id: '/progress/prefectures',
    path: '/progress/prefectures',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutProgressMunicipalitiesRoute =
  AdminLayoutProgressMunicipalitiesRouteImport.update({
    id: '/progress/municipalities',
    path: '/progress/municipalities',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/meetings/$meetingId': typeof MeetingsMeetingIdRoute
  '/meetings/': typeof MeetingsIndexRoute
  '/municipalities/': typeof MunicipalitiesIndexRoute
  '/search/': typeof SearchIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/sign-in/': typeof authSignInIndexRoute
  '/sign-up/': typeof authSignUpIndexRoute
  '/admin/': typeof AdminLayoutIndexRoute
  '/admin/progress/municipalities': typeof AdminLayoutProgressMunicipalitiesRoute
  '/admin/progress/prefectures': typeof AdminLayoutProgressPrefecturesRoute
  '/admin/progress/years': typeof AdminLayoutProgressYearsRoute
  '/admin/scrapers/$jobId': typeof AdminLayoutScrapersJobIdRoute
  '/admin/progress/': typeof AdminLayoutProgressIndexRoute
  '/admin/scrapers/': typeof AdminLayoutScrapersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/meetings/$meetingId': typeof MeetingsMeetingIdRoute
  '/meetings': typeof MeetingsIndexRoute
  '/municipalities': typeof MunicipalitiesIndexRoute
  '/search': typeof SearchIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/sign-in': typeof authSignInIndexRoute
  '/sign-up': typeof authSignUpIndexRoute
  '/admin': typeof AdminLayoutIndexRoute
  '/admin/progress/municipalities': typeof AdminLayoutProgressMunicipalitiesRoute
  '/admin/progress/prefectures': typeof AdminLayoutProgressPrefecturesRoute
  '/admin/progress/years': typeof AdminLayoutProgressYearsRoute
  '/admin/scrapers/$jobId': typeof AdminLayoutScrapersJobIdRoute
  '/admin/progress': typeof AdminLayoutProgressIndexRoute
  '/admin/scrapers': typeof AdminLayoutScrapersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/meetings/$meetingId': typeof MeetingsMeetingIdRoute
  '/meetings/': typeof MeetingsIndexRoute
  '/municipalities/': typeof MunicipalitiesIndexRoute
  '/search/': typeof SearchIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/(auth)/sign-in/': typeof authSignInIndexRoute
  '/(auth)/sign-up/': typeof authSignUpIndexRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
  '/admin/_layout/progress/municipalities': typeof AdminLayoutProgressMunicipalitiesRoute
  '/admin/_layout/progress/prefectures': typeof AdminLayoutProgressPrefecturesRoute
  '/admin/_layout/progress/years': typeof AdminLayoutProgressYearsRoute
  '/admin/_layout/scrapers/$jobId': typeof AdminLayoutScrapersJobIdRoute
  '/admin/_layout/progress/': typeof AdminLayoutProgressIndexRoute
  '/admin/_layout/scrapers/': typeof AdminLayoutScrapersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/meetings/$meetingId'
    | '/meetings/'
    | '/municipalities/'
    | '/search/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/sign-in/'
    | '/sign-up/'
    | '/admin/'
    | '/admin/progress/municipalities'
    | '/admin/progress/prefectures'
    | '/admin/progress/years'
    | '/admin/scrapers/$jobId'
    | '/admin/progress/'
    | '/admin/scrapers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/meetings/$meetingId'
    | '/meetings'
    | '/municipalities'
    | '/search'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/sign-in'
    | '/sign-up'
    | '/admin'
    | '/admin/progress/municipalities'
    | '/admin/progress/prefectures'
    | '/admin/progress/years'
    | '/admin/scrapers/$jobId'
    | '/admin/progress'
    | '/admin/scrapers'
  id:
    | '__root__'
    | '/'
    | '/admin/_layout'
    | '/meetings/$meetingId'
    | '/meetings/'
    | '/municipalities/'
    | '/search/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/(auth)/sign-in/'
    | '/(auth)/sign-up/'
    | '/admin/_layout/'
    | '/admin/_layout/progress/municipalities'
    | '/admin/_layout/progress/prefectures'
    | '/admin/_layout/progress/years'
    | '/admin/_layout/scrapers/$jobId'
    | '/admin/_layout/progress/'
    | '/admin/_layout/scrapers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  MeetingsMeetingIdRoute: typeof MeetingsMeetingIdRoute
  MeetingsIndexRoute: typeof MeetingsIndexRoute
  MunicipalitiesIndexRoute: typeof MunicipalitiesIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  authSignInIndexRoute: typeof authSignInIndexRoute
  authSignUpIndexRoute: typeof authSignUpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/municipalities/': {
      id: '/municipalities/'
      path: '/municipalities'
      fullPath: '/municipalities/'
      preLoaderRoute: typeof MunicipalitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/': {
      id: '/meetings/'
      path: '/meetings'
      fullPath: '/meetings/'
      preLoaderRoute: typeof MeetingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/$meetingId': {
      id: '/meetings/$meetingId'
      path: '/meetings/$meetingId'
      fullPath: '/meetings/$meetingId'
      preLoaderRoute: typeof MeetingsMeetingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/(auth)/sign-up/': {
      id: '/(auth)/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof authSignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in/': {
      id: '/(auth)/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof authSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/scrapers/': {
      id: '/admin/_layout/scrapers/'
      path: '/scrapers'
      fullPath: '/admin/scrapers/'
      preLoaderRoute: typeof AdminLayoutScrapersIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/progress/': {
      id: '/admin/_layout/progress/'
      path: '/progress'
      fullPath: '/admin/progress/'
      preLoaderRoute: typeof AdminLayoutProgressIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/scrapers/$jobId': {
      id: '/admin/_layout/scrapers/$jobId'
      path: '/scrapers/$jobId'
      fullPath: '/admin/scrapers/$jobId'
      preLoaderRoute: typeof AdminLayoutScrapersJobIdRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/progress/years': {
      id: '/admin/_layout/progress/years'
      path: '/progress/years'
      fullPath: '/admin/progress/years'
      preLoaderRoute: typeof AdminLayoutProgressYearsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/progress/prefectures': {
      id: '/admin/_layout/progress/prefectures'
      path: '/progress/prefectures'
      fullPath: '/admin/progress/prefectures'
      preLoaderRoute: typeof AdminLayoutProgressPrefecturesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/progress/municipalities': {
      id: '/admin/_layout/progress/municipalities'
      path: '/progress/municipalities'
      fullPath: '/admin/progress/municipalities'
      preLoaderRoute: typeof AdminLayoutProgressMunicipalitiesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface AdminLayoutRouteChildren {
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
  AdminLayoutProgressMunicipalitiesRoute: typeof AdminLayoutProgressMunicipalitiesRoute
  AdminLayoutProgressPrefecturesRoute: typeof AdminLayoutProgressPrefecturesRoute
  AdminLayoutProgressYearsRoute: typeof AdminLayoutProgressYearsRoute
  AdminLayoutScrapersJobIdRoute: typeof AdminLayoutScrapersJobIdRoute
  AdminLayoutProgressIndexRoute: typeof AdminLayoutProgressIndexRoute
  AdminLayoutScrapersIndexRoute: typeof AdminLayoutScrapersIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
  AdminLayoutProgressMunicipalitiesRoute:
    AdminLayoutProgressMunicipalitiesRoute,
  AdminLayoutProgressPrefecturesRoute: AdminLayoutProgressPrefecturesRoute,
  AdminLayoutProgressYearsRoute: AdminLayoutProgressYearsRoute,
  AdminLayoutScrapersJobIdRoute: AdminLayoutScrapersJobIdRoute,
  AdminLayoutProgressIndexRoute: AdminLayoutProgressIndexRoute,
  AdminLayoutScrapersIndexRoute: AdminLayoutScrapersIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  MeetingsMeetingIdRoute: MeetingsMeetingIdRoute,
  MeetingsIndexRoute: MeetingsIndexRoute,
  MunicipalitiesIndexRoute: MunicipalitiesIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  authSignInIndexRoute: authSignInIndexRoute,
  authSignUpIndexRoute: authSignUpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
